export const impliedVolOracleAbi = [
  {
    name: "getRealizedVol",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "vol", type: "uint256" }],
  },
  {
    name: "simulateRealizedVol",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "vol", type: "uint256" }],
  },
  {
    name: "getEwmaVariance",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "variance", type: "uint256" }],
  },
  {
    name: "getImpliedVol",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "vol", type: "uint256" }],
  },
  {
    name: "getEffectiveImpliedVol",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "vol", type: "uint256" }],
  },
  {
    name: "getVolRiskPremium",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "premium", type: "int256" }],
  },
  {
    name: "observationCount",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "isInitialized",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "lastObservationTimestamp",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "lastObservedSpot",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "lambda",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "ewmaVariance",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;
